# Generated by Django 2.2 on 2021-07-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_quotes',
            field=models.CharField(max_length=5000),
        ),
    ]
